USE SUPERMAYORISTA	 
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = 'DM_SUPERMAYORISTA')
	BEGIN
		DROP DATABASE DM_SUPERMAYORISTA
	END
GO

CREATE DATABASE DM_SUPERMAYORISTA
GO

USE DM_SUPERMAYORISTA
GO

CREATE TABLE DIM_VENDEDOR (
	VENDEDOR_KEY INT IDENTITY(1,1) NOT NULL,
	COD_VENDEDOR VARCHAR(9) NOT NULL,
	NOMBRE_VENDEDOR VARCHAR(65) NOT NULL,
	SUPERVISOR INT NOT NULL,
	PRIMARY KEY(VENDEDOR_KEY)
)
GO

CREATE TABLE DIM_DOCUMENTO (
	DOCUMENTO_KEY INT IDENTITY(1,1) NOT NULL,
	COD_TIPO_DOCUMENTO VARCHAR(8) NOT NULL,
	TIPO_DOCUMENTO VARCHAR(26) NOT NULL,
	INDICADOR VARCHAR(1) NOT NULL
	PRIMARY KEY(DOCUMENTO_KEY)
)
GO

CREATE TABLE DIM_VENTA (
	VENTA_KEY INT IDENTITY(1,1) NOT NULL,
	COD_VENTA VARCHAR(13) NOT NULL,
	ESTADO VARCHAR(13) NOT NULL,
	PRIMARY KEY(VENTA_KEY)
)
GO

CREATE TABLE DIM_BANCO (
	BANCO_KEY INT IDENTITY(1,1) NOT NULL,
	COD_BANCO VARCHAR(7) NOT NULL,
	NOMBRE_BANCO VARCHAR(65) NOT NULL,
	COMISION FLOAT NOT NULL,
	PRIMARY KEY(BANCO_KEY)
)
GO

CREATE TABLE DIM_PRODUCTO (
	PRODUCTO_KEY INT IDENTITY(1,1) NOT NULL,
	COD_PRODUCTO VARCHAR(12) NOT NULL,
	NOMBRE_PRODUCTO VARCHAR(195) NOT NULL,
	FK_SUBCATEGORIA INT NOT NULL,
	PRIMARY KEY(PRODUCTO_KEY)
)
GO

CREATE TABLE DIM_SUBCATEGORIA (
	SUBCATEGORIA_KEY INT IDENTITY(1,1) NOT NULL,
	DESCRIPCION VARCHAR(65) NOT NULL,
	FK_CATEGORIA INT NOT NULL,
	PRIMARY KEY(SUBCATEGORIA_KEY)
)
GO

CREATE TABLE DIM_CATEGORIA (
	CATEGORIA_KEY INT IDENTITY(1,1) NOT NULL,
	DESCRIPCION VARCHAR(65) NOT NULL,
	PRIMARY KEY(CATEGORIA_KEY)
)
GO

CREATE TABLE DIM_CLIENTE (
	--CLIENTE_KEY INT IDENTITY(1,1) NOT NULL,
	DNI_CLIENTE VARCHAR(14) NOT NULL,
	FK_DISTRITO INT NOT NULL,
	--PRIMARY KEY(CLIENTE_KEY)
	PRIMARY KEY(DNI_CLIENTE)
)
GO


CREATE TABLE DIM_DISTRITO (
	DISTRITO_KEY INT IDENTITY(1,1) NOT NULL,
	NOMBRE_DISTRITO VARCHAR(65) NOT NULL,
	UBIGEO VARCHAR(13) NOT NULL,
	PUNTO_GEOGRAFICO VARCHAR(65) NOT NULL,
	FK_DEPARTAMENTO INT NOT NULL,
	PRIMARY KEY(DISTRITO_KEY)
)
GO

CREATE TABLE DIM_DEPARTAMENTO (
	DEPARTAMENTO_KEY INT IDENTITY(1,1) NOT NULL,
	NOMBRE_DEPARTAMENTO VARCHAR(65) NOT NULL,
	PRIMARY KEY(DEPARTAMENTO_KEY)
)
GO

CREATE TABLE DIM_PERIODO (
	PERIODO_KEY INT IDENTITY(1,1) NOT NULL,
	COD_PERIODO VARCHAR(20) NOT NULL,
	FECHA DATE NOT NULL,
	ANIO INT NOT NULL,
	MES INT NOT NULL,
	DIA INT NOT NULL,
	PRIMARY KEY(PERIODO_KEY)
)
GO

CREATE TABLE FACT_SUPERMAYORISTA (
	FK_VENTA INT NOT NULL,
	--FK_CLIENTE INT NOT NULL,
	FK_CLIENTE VARCHAR(14) NOT NULL,
	FK_VENDEDOR INT NOT NULL,
	FK_BANCO INT NOT NULL,
	FK_PRODUCTO INT NOT NULL,
	FK_PERIODO INT NOT NULL,
	FK_TIPO_DOCUMENTO INT NOT NULL,
	CANTIDAD_PRODUCTO INT NOT NULL,
	PRECIO_UNIT FLOAT NOT NULL
)
GO

ALTER TABLE FACT_SUPERMAYORISTA
ADD CONSTRAINT FK__FACT_SUPER__FK_VENTA FOREIGN KEY (FK_VENTA) REFERENCES DIM_VENTA(VENTA_KEY);

ALTER TABLE FACT_SUPERMAYORISTA
ADD CONSTRAINT FK__FACT_SUPER__FK_CLIENTE FOREIGN KEY (FK_CLIENTE) REFERENCES DIM_CLIENTE(CLIENTE_KEY);

--PRUEBA
ALTER TABLE FACT_SUPERMAYORISTA
ADD CONSTRAINT FK__FACT_SUPER__FK_CLIENTE FOREIGN KEY (FK_CLIENTE) REFERENCES DIM_CLIENTE(DNI_CLIENTE);
--

ALTER TABLE FACT_SUPERMAYORISTA
ADD CONSTRAINT FK__FACT_SUPER__FK_VENDEDOR FOREIGN KEY (FK_VENDEDOR) REFERENCES DIM_VENDEDOR (VENDEDOR_KEY);

ALTER TABLE FACT_SUPERMAYORISTA
ADD CONSTRAINT FK__FACT_SUPER__FK_BANCO FOREIGN KEY (FK_BANCO) REFERENCES DIM_BANCO (BANCO_KEY);

ALTER TABLE FACT_SUPERMAYORISTA
ADD CONSTRAINT FK__FACT_SUPER__FK_PRODUCTO FOREIGN KEY (FK_PRODUCTO) REFERENCES DIM_PRODUCTO (PRODUCTO_KEY);

ALTER TABLE FACT_SUPERMAYORISTA
ADD CONSTRAINT FK__FACT_SUPER__FK_PERIODO FOREIGN KEY (FK_PERIODO) REFERENCES DIM_PERIODO(PERIODO_KEY);
GO

ALTER TABLE FACT_SUPERMAYORISTA
ADD CONSTRAINT FK__FACT_SUPER__FK_TIPO_DOCUMENTO FOREIGN KEY (FK_TIPO_DOCUMENTO) REFERENCES DIM_DOCUMENTO(DOCUMENTO_KEY);
GO

--PRODUCTO
ALTER TABLE DIM_PRODUCTO
ADD CONSTRAINT FK__DIM_PROD__FK_SUBCATEGORIA FOREIGN KEY (FK_SUBCATEGORIA) REFERENCES DIM_SUBCATEGORIA (SUBCATEGORIA_KEY);
GO

ALTER TABLE DIM_SUBCATEGORIA
ADD CONSTRAINT FK__DIM_SUBC__FK_CATEGORIA FOREIGN KEY (FK_CATEGORIA) REFERENCES DIM_CATEGORIA (CATEGORIA_KEY);
GO

--CLIENTE
ALTER TABLE DIM_CLIENTE
ADD CONSTRAINT FK__DIM_CLI__FK_DISTRITO FOREIGN KEY (FK_DISTRITO) REFERENCES DIM_DISTRITO (DISTRITO_KEY);
GO

ALTER TABLE DIM_DISTRITO
ADD CONSTRAINT FK__DIM_DIS__FK_DEPARTAMENTO FOREIGN KEY (FK_DEPARTAMENTO) REFERENCES DIM_DEPARTAMENTO (DEPARTAMENTO_KEY);
GO

--VENDEDOR
ALTER TABLE DIM_VENDEDOR
ADD CONSTRAINT FK__DIM_VEN__FK_SUPERVISOR FOREIGN KEY (SUPERVISOR) REFERENCES DIM_VENDEDOR (VENDEDOR_KEY);
GO